package com.nashss.se.yodaservice.enums;


public class COMP_TEST_DATA {
    private static String data = "{\"MEDICATION\":{\"GENERIC_NAME\":{\"loratadine\":[{}]},\"BRAND_NAME\":{\"Ortho Tri-Cyclen\":[{}],\"Allegra\":[{\"Traits\":[\"PAST_HISTORY\"]},{},{}],\"Nasonex\":[{\"ROUTE_OR_MODE\":[\"each nostril\"],\"DOSAGE\":[\"two sprays\"],\"DURATION\":[\"three weeks\"]}],\"Claritin\":[{\"Traits\":[\"PAST_HISTORY\"]}],\"Zyrtec\":[{\"Traits\":[\"PAST_HISTORY\"]},{}]}},\"ANATOMY\":{\"SYSTEM_ORGAN_SITE\":{\"nasal\":[{}],\"nostril\":[{}],\"Lungs\":[{}],\"throat\":[{}],\"HEENT\":[{}],\"TMs\":[{}],\"Neck\":[{}],\"Nasal mucosa\":[{}]}},\"MEDICAL_CONDITION\":{\"TYPE\":{\"allergies\":[{\"Traits\":[\"SYMPTOM\"]}],\"flaring up.\":[{}],\"erythematous\":[{\"QUALITY\":[\"mildly\"],\"Traits\":[\"SIGN\"],\"SYSTEM_ORGAN_SITE\":[\"HEENT\",\"throat\"]},{\"Traits\":[\"SIGN\"],\"SYSTEM_ORGAN_SITE\":[\"HEENT\",\"Nasal mucosa\"]}],\"adenopathy\":[{\"Traits\":[\"SIGN\",\"NEGATION\"],\"SYSTEM_ORGAN_SITE\":[\"TMs\",\"Neck\"]}],\"swollen\":[{\"Traits\":[\"SIGN\"],\"SYSTEM_ORGAN_SITE\":[\"HEENT\",\"Nasal mucosa\"]}],\"clear\":[{\"Traits\":[\"SIGN\"],\"SYSTEM_ORGAN_SITE\":[\"HEENT\",\"TMs\"]}],\"asthma\":[{\"Traits\":[\"DIAGNOSIS\"]}],\"exudate\":[{\"Traits\":[\"SIGN\",\"NEGATION\"],\"SYSTEM_ORGAN_SITE\":[\"HEENT\",\"throat\"]}],\"drainage\":[{\"QUALITY\":[\"clear\"],\"Traits\":[\"SIGN\"],\"SYSTEM_ORGAN_SITE\":[\"HEENT\"]}],\"rhinitis\":[{\"QUALITY\":[\"Allergic\"],\"Traits\":[\"DIAGNOSIS\"],\"SYSTEM_ORGAN_SITE\":[\"Lungs\"]}],\"Supple\":[{\"Traits\":[\"SIGN\"],\"SYSTEM_ORGAN_SITE\":[\"HEENT\",\"TMs\",\"Neck\"]}],\"Clear\":[{\"Traits\":[\"SIGN\"],\"SYSTEM_ORGAN_SITE\":[\"Lungs\"]}]}},\"TIME_EXPRESSION\":{},\"BEHAVIORAL_ENVIRONMENTAL_SOCIAL\":{\"TYPE\":{\"white\":[{}],\"female\":[{}]}},\"PROTECTED_HEALTH_INFORMATION\":{\"DATE\":{\"summer\":[{}]},\"ADDRESS\":{\"Seattle\":[{}]},\"AGE\":{\"23\":[{}]}},\"TEST_TREATMENT_PROCEDURE\":{\"TEST_NAME\":{\"blood pressure\":[{\"TEST_VALUE\":[\"124/78.\"]}],\"Vitals\":[{\"ATTRIBUTE TYPE\":[\"pounds\"]}],\"Weight\":[{\"ATTRIBUTE TYPE\":[\"pounds\"],\"TEST_VALUE\":[\"130\"]}]},\"TREATMENT_NAME\":{\"nasal sprays\":[{\"Traits\":[\"NEGATION\"]}],\"MEDICATIONS\":[{}],\"sprays\":[{}],\"medication\":[{\"Traits\":[\"NEGATION\"]},{}],\"medicine\":[{}]}}}";

    public static String getData() {
        return data;
    }
}
